// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Telemetry interface {
	IsTelemetry()
}

// _Entity represents all types with @key
type _Entity interface {
	Is_Entity()
}

type Device struct {
	ID string `json:"id"`
}

func (Device) Is_Entity() {}

type Entity struct {
	FindDeviceByID *Device `json:"findDeviceByID"`
}

type Origin struct {
	Device *Device        `json:"device"`
	Pos    *WGS84Position `json:"pos"`
}

type Problemreport struct {
	From   *Origin `json:"from"`
	When   string  `json:"when"`
	Depth  float64 `json:"depth"`
	Manual *bool   `json:"manual"`
}

func (Problemreport) IsTelemetry() {}

type WGS84Position struct {
	Lon float64 `json:"lon"`
	Lat float64 `json:"lat"`
}
