// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

// _Entity represents all types with @key
type _Entity interface {
	Is_Entity()
}

type Entity struct {
	FindProblemReportCategoryByID *ProblemReportCategory `json:"findProblemReportCategoryByID"`
	FindProblemReportByID         *ProblemReport         `json:"findProblemReportByID"`
}

type ProblemReport struct {
	ID   string         `json:"id"`
	Pos  *WGS84Position `json:"pos"`
	Type string         `json:"type"`
}

func (ProblemReport) Is_Entity() {}

type ProblemReportCategory struct {
	ID         string `json:"id"`
	Label      string `json:"label"`
	ReportType string `json:"reportType"`
}

func (ProblemReportCategory) Is_Entity() {}

type ProblemReportCreateResource struct {
	Pos  *ReportPosition `json:"pos"`
	Type string          `json:"type"`
}

type ReportPosition struct {
	Lat float64 `json:"lat"`
	Lon float64 `json:"lon"`
}

type WGS84Position struct {
	Lon float64 `json:"lon"`
	Lat float64 `json:"lat"`
}
